products/urls.py
from django.conf.urls import patterns, url

from products import views

urlpatterns = patterns('',
    url(r'^$', views.ProductListView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.ProductDetailView.as_view(), name='detail'),
    url(r'create/$', views.ProductCreateView.as_view(), name='create'),
)

tasdurab/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from tasdurab import views

urlpatterns = patterns('',
    url(r'^$', views.home, name='home'),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^login$', 'django_cas_ng.views.login', name='login'),
    url(r'^logout$', 'django_cas_ng.views.logout', name='logout'),
    url(r'^admin/', include(admin.site.urls)),
)

users/urls.py
from django.conf.urls import patterns, url

from users.views import UserDetailView, UserUpdateView

urlpatterns = patterns('',
    url(r'^(?P<pk>\d+)/$', UserDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/register$', UserUpdateView.as_view(success_url='/'), name='register'),
)

infos/models.py
from django.db import models
from tasdurab import settings

import os

class Info(models.Model):

    title = models.CharField(max_length=255, verbose_name='Titre')
    description = models.TextField(max_length=2048, verbose_name= 'Description')
    image = models.ImageField(
        upload_to = os.path.join(settings.BASE_DIR, 'infos/static/infos/images/'),
    )
    pub_date = models.DateTimeField()

    class Meta:
        verbose_name = u'Info'
        verbose_name_plural = u'Infos'
        ordering = ['pub_date']

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def getFileName(self):
        return self.image.url.split('/')[-1]

products/models.py
# -*- coding: utf-8 -*

from django.db import models
from users.models import User
from tasdurab import settings
import os


class Category(models.Model):

    title = models.CharField(max_length=255, verbose_name='Nom')
    image = models.ImageField(
        upload_to = os.path.join(settings.BASE_DIR, 'products/static/categories/images'),
        default = os.path.join(settings.BASE_DIR, 'products/static/categories/images/default.png')
        )

    class Meta:
        verbose_name = u'Catégorie'
        verbose_name_plural = u'Catégories'

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_filename(self):
        return self.image.url.split('/')[-1]


class Product(models.Model):

    category = models.ForeignKey(Category, verbose_name= u'Catégorie')
    title = models.CharField(max_length=255, verbose_name='Nom')
    description = models.CharField(max_length=2048, blank=True, null=True, verbose_name= 'Description')
    expiry_date = models.DateField(verbose_name= u'Date de péremption')
    owner = models.ForeignKey(User, blank=True, null=True)
    quantity = models.PositiveIntegerField(default=1, verbose_name= u'Quantité')
    is_opened = models.BooleanField(default= False, verbose_name= u'Déjà Ouvert?')


    created_at = models.DateTimeField(auto_now_add=True, verbose_name = 'Date de publication')

    class Meta:
        verbose_name = u'Produit'
        verbose_name_plural = u'Produits'
        ordering = ['expiry_date']

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('products:index')

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<head>
  <meta charset="utf-8">
  <title>{% block title %}T'as du RAB ?{% endblock %}</title>
  <meta name="description" content="T'asdurab?">
  <meta name="author" content="github.com/Guitoof">

  <!-- Mobile Meta -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Favicon -->
  <link rel="shortcut icon" href="images/favicon.ico">

  <!-- Web Fonts -->
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700,300&amp;subset=latin,latin-ext' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=PT+Serif' rel='stylesheet' type='text/css'>

  <!-- Bootstrap core CSS -->
  <link href="{% static "bootstrap/css/bootstrap.css" %}" rel="stylesheet">

  <!-- Font Awesome CSS -->
  <link href="{% static "fonts/font-awesome/css/font-awesome.css" %}" rel="stylesheet">

  <!-- Fontello CSS -->
  <link href="{% static "fonts/fontello/css/fontello.css" %}" rel="stylesheet">

  <!-- Plugins -->
  <link href="{% static "plugins/rs-plugin/css/settings.css" %}" media="screen" rel="stylesheet">
  <link href="{% static "plugins/rs-plugin/css/extralayers.css" %}" media="screen" rel="stylesheet">
  <link href="{% static "plugins/magnific-popup/magnific-popup.css" %}" rel="stylesheet">
  <link href="{% static "css/animations.css" %}" rel="stylesheet">
  <link href="{% static "plugins/owl-carousel/owl.carousel.css" %}" rel="stylesheet">

  <!-- iDea core CSS file -->
  <link href="{% static "css/style.css" %}" rel="stylesheet">

  <!-- Color Scheme (In order to change the color scheme, replace the red.css with the color scheme that you prefer)-->
  <link href="{% static "css/skins/tasdurab_green.css" %}" rel="stylesheet">

  <!-- Custom css -->
  <link href="{% static "css/custom.css" %}" rel="stylesheet">

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

<!-- body classes:
"boxed": boxed layout mode e.g. <body class="boxed">
"pattern-1 ... pattern-9": background patterns for boxed layout mode e.g. <body class="boxed pattern-1">
-->
<body class="front no-trans">
  <!-- scrollToTop -->
  <!-- ================ -->
  <div class="scrollToTop"><i class="icon-up-open-big"></i></div>

  <!-- page wrapper start -->
  <!-- ================ -->
  <div class="page-wrapper">

    <!-- header start classes:
    fixed: fixed navigation mode (sticky menu) e.g. <header class="header fixed clearfix">
    dark: dark header version e.g. <header class="header dark clearfix">
    ================ -->
    <header class="header fixed clearfix">
      <div class="container">
        <div class="row">
          <div class="col-md-3">

            <!-- header-left start -->
            <!-- ================ -->
            <div class="header-left clearfix">

              <!-- logo -->
              <div class="logo">
                <a href="{% url 'products:index' %}"><img id="logo" src="{% static "images/logo_18_85px.svg" %}" alt="iDea"></a>
              </div>

              <!-- name-and-slogan -->
              <div class="site-slogan">
                T'as du RAB ?
              </div>

            </div>
            <!-- header-left end -->

          </div>
          <div class="col-md-9">

            <!-- header-right start -->
            <!-- ================ -->
            <div class="header-right clearfix">

              {% include "menu.html" %}

            </div>
            <!-- header-right end -->

          </div>
        </div>
      </div>
    </header>
    <!-- header end -->

    {% block pageIntro %}
    <!-- page-intro start-->
    <!-- ================ -->
    <!-- <div class="page-intro">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <ol class="breadcrumb">
              <li><i class="fa fa-home pr-10"></i><a href="{% url 'products:index' %}">Produits</a></li>
            </ol>
          </div>
        </div>
      </div>
    </div> -->
    <!-- page-intro end -->
    {% endblock %}

    {% block content %}
    {% endblock %}

    <!-- footer start (Add "light" class to #footer in order to enable light footer) -->
    <!-- ================ -->
    <footer id="footer">

      <!-- .subfooter start -->
      <!-- ================ -->
      <div class="subfooter">
        <div class="container">
          <div class="row">
            <div class="col-md-6">
            </div>
            <div class="col-md-6">
              <nav class="navbar navbar-default" role="navigation">
                <!-- Toggle get grouped for better mobile display -->
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-2">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                </div>
                <div class="collapse navbar-collapse" id="navbar-collapse-2">
                  <ul class="nav navbar-nav">
                    <li><a href="{% url 'products:index' %}">Produits</a></li>
                    <li><a href="{% url 'admin:index' %}">Admin</a></li>
                  </ul>
                </div>
              </nav>
            </div>
          </div>
        </div>
      </div>
      <!-- .subfooter end -->

    </footer>
    <!-- footer end -->

  </div>
  <!-- page-wrapper end -->

  <!-- JavaScript files placed at the end of the document so the pages load faster
  ================================================== -->
  <!-- Jquery and Bootstap core js files -->
  <script type="text/javascript" src="{% static "plugins/jquery.min.js" %}"></script>
  <script type="text/javascript" src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>

  <!-- Modernizr javascript -->
  <script type="text/javascript" src="{% static "plugins/modernizr.js" %}"></script>

  <!-- jQuery REVOLUTION Slider  -->
  <script type="text/javascript" src="{% static "plugins/rs-plugin/js/jquery.themepunch.tools.min.js" %}"></script>
  <script type="text/javascript" src="{% static "plugins/rs-plugin/js/jquery.themepunch.revolution.min.js" %}"></script>

  <!-- Isotope javascript -->
  <script type="text/javascript" src="{% static "plugins/isotope/isotope.pkgd.min.js" %}"></script>

  <!-- Owl carousel javascript -->
  <script type="text/javascript" src="{% static "plugins/owl-carousel/owl.carousel.js" %}"></script>

  <!-- Magnific Popup javascript -->
  <script type="text/javascript" src="{% static "plugins/magnific-popup/jquery.magnific-popup.min.js" %}"></script>

  <!-- Appear javascript -->
  <script type="text/javascript" src="{% static "plugins/jquery.appear.js" %}"></script>

  <!-- Count To javascript -->
  <script type="text/javascript" src="{% static "plugins/jquery.countTo.js" %}"></script>

  <!-- Parallax javascript -->
  <script src="{% static "plugins/jquery.parallax-1.1.3.js" %}"></script>

  <!-- Contact form -->
  <script src="{% static "plugins/jquery.validate.js" %}"></script>

  <!-- Initialization of Plugins -->
  <script type="text/javascript" src="{% static "js/template.js" %}"></script>


  <!-- Custom Scripts -->
  <script type="text/javascript" src="{% static "js/custom.js" %}"></script>

  <!-- Product form -->
  <script src="{% static "products/js/products.js" %}"></script>

</body>
</html>

templates/home.html
{% extends "base.html" %}

{% load staticfiles %}

{% block content %}

<!-- slideshow start -->
				<!-- ================ -->
				<div class="slideshow white-bg">

					<!-- slider revolution start -->
					<!-- ================ -->
					<div class="slider-banner-container">
						<div class="slider-banner-fullscreen">
							<ul>
								{% for info in info_list %}
								<!-- slide 1 start -->
								<li data-transition="fade" data-slotamount="7" data-masterspeed="1000" data-saveperformance="on" data-title="Slide 1" class="light-translucent-bg">

								<!-- main image -->
								<img src="{% static "infos/images/" %}{{ info.getFileName }}"  alt="slidebg1" data-bgposition="center top" data-bgfit="cover" data-bgrepeat="no-repeat">

								<!-- LAYER NR. 1 -->
								<div class="tp-caption very_large_text black sfl tp-resizeme"
									data-x="center"
									data-y="70"
									data-speed="600"
									data-start="0"
									data-end="10000"
									data-endspeed="600">{{ info }}
								</div>

								<!-- LAYER NR. 2 -->
								<div class="tp-caption sfr small_thin_dark text-center tp-resizeme"
									data-x="center"
									data-y="190" 
									data-speed="600"
									data-start="0"
									data-end="10000"
									data-endspeed="600"> {{ info.description }} 
								</div>
<!--  -->

								<!-- LAYER NR. 3 -->
								<!-- <div class="tp-caption tp-resizeme sfl"
									data-x="center"
									data-y="350"
									data-speed="600"
									data-start="0"
									data-end="10000"
									data-endspeed="600"><a href="portfolio-item.html" class="btn btn-dark btn-lg">En savoir plus <i class="fa fa-angle-double-right pl-10"></i></a>
								</div> -->

								</li>
								<!-- slide 1 end -->
								{% endfor %}


							</ul>
						</div>
					</div>
					<!-- slider revolution end -->

				</div>
				<!-- slideshow end -->


				<!-- section start -->
			<!-- ================ -->
			<div class="section clearfix object-non-visible" data-animation-effect="fadeInUpSmall" data-effect-delay="300">

				<div class="container">
					<div class="row">
						<div class="col-md-12">

							<h2>Les catégories de produits</h2>
							<div class="separator-2"></div>

							<!-- isotope filters start/ Need to change the "data-filter" by...? -->
							<!-- <div class="filters">
								<ul class="nav nav-pills">
									<li class="active"><a href="#" data-filter="*">Tout</a></li>
									<li><a href="#" data-filter=".web-design">Laitage</a></li>
									<li><a href="#" data-filter=".app-development">Fruits/Legumes</a></li>
									<li><a href="#" data-filter=".site-building">Oeufs</a></li>
									<li><a href="#" data-filter=".site-building">Plats cuisinés</a></li>
									<li><a href="#" data-filter=".site-building">Viande</a></li>
									<li><a href="#" data-filter=".site-building">Sauces</a></li>
								</ul>
							</div> -->
							<!-- isotope filters end -->

						<div class="isotope-container row grid-space-20">

							{% for category in category_list %}
							<!-- portfolio items start -->
								<div class="col-sm-6 col-md-4 isotope-item web-design">
									<div class="image-box">
										<div class="overlay-container">
											<img src="{% static "categories/images/" %}{{ category.get_filename }}" alt="">
											<a href="{% url 'products:index' %}?category={{ category.id }}" class="overlay small">
												<i class="fa fa-link"></i>
												<span>{{ category }}</span>
											</a>
										</div>
										<a href="{% url 'products:index' %}?category={{ category.id }}" class="btn btn-light-gray btn-lg btn-block">{{ category }}</a>
									</div>
								</div>
							<!-- portfolio items end -->
							{% endfor %}

						</div>

						</div>
					</div>
				</div>

			</div>
			<!-- section end -->


{% endblock %}

templates/menu.html
{% load staticfiles %}

<!-- main-navigation start -->
<!-- ================ -->
<div class="main-navigation animated">

  <!-- navbar start -->
  <!-- ================ -->
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">

      <!-- Toggle get grouped for better mobile display -->
      <!-- <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div> -->

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li>
            <a href="{% url 'home' %}">Accueil</a>
          </li>
          <li>
            <a href="{% url 'products:index' %}">Produits</a>
          </li>
          {% if user.is_authenticated %}
          <li class="dropdown">
            <a href="{% url 'users:detail' user.id %}" class="dropdown-toggle" data-toggle="dropdown">{{ user }}</a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'users:detail' user.id %}">Mon profil</a></li>
              <li><a href="{% url 'logout' %}">Déconnexion</a></li>
            </ul>
          </li>
          {%else%}
          <li><a href="{% url 'login' %}">Connexion</a></li>
          {%endif%}
          </li>
        </ul>
      </div>

    </div>
  </nav>
  <!-- navbar end -->

</div>
<!-- main-navigation end -->