products/urls.py
from django.conf.urls import patterns, url

from products import views

urlpatterns = patterns('',
    url(r'^$', views.ProductListView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.ProductDetailView.as_view(), name='detail'),
    url(r'create/$', views.ProductCreateView.as_view(), name='create'),
)

tasdurab/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from tasdurab import views

urlpatterns = patterns('',
    url(r'^$', views.home, name='home'),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^login$', 'django_cas_ng.views.login', name='login'),
    url(r'^logout$', 'django_cas_ng.views.logout', name='logout'),
    url(r'^admin/', include(admin.site.urls)),
)

users/urls.py
from django.conf.urls import patterns, url

from users.views import UserDetailView, UserUpdateView

urlpatterns = patterns('',
    url(r'^(?P<pk>\d+)/$', UserDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/register$', UserUpdateView.as_view(success_url='/'), name='register'),
)

products/models.py
# -*- coding: utf-8 -*

from django.db import models
from users.models import User
from tasdurab import settings
import os


class Category(models.Model):

    title = models.CharField(max_length=255, verbose_name='Nom')
    image = models.ImageField(
        upload_to = os.path.join(settings.BASE_DIR, 'products/static/categories/images'),
        default = os.path.join(settings.BASE_DIR, 'products/static/categories/images/default.png')
        )

    class Meta:
        verbose_name = u'Catégorie'
        verbose_name_plural = u'Catégories'

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_filename(self):
        return self.image.url.split('/')[-1]


class Product(models.Model):

    category = models.ForeignKey(Category, verbose_name= u'Catégorie')
    title = models.CharField(max_length=255, verbose_name='Nom')
    description = models.CharField(max_length=2048, blank=True, null=True, verbose_name= 'Description')
    expiry_date = models.DateField(verbose_name= u'Date de péremption')
    owner = models.ForeignKey(User, blank=True, null=True)
    quantity = models.PositiveIntegerField(default=1, verbose_name= u'Quantité')
    is_opened = models.BooleanField(default= False, verbose_name= u'Déjà Ouvert?')


    created_at = models.DateTimeField(auto_now_add=True, verbose_name = 'Date de publication')

    class Meta:
        verbose_name = u'Produit'
        verbose_name_plural = u'Produits'
        ordering = ['expiry_date']

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('products:index')

products/forms.py
# -*- coding: utf-8 -*

from django.forms import ModelForm
from products.models import Product

# Fields
from django.forms import TextInput, Select, Textarea, DateInput, NumberInput, CheckboxInput

class ProductCreateForm(ModelForm):

    class Meta:
        model = Product
        exclude = ('owner',)
        widgets = {
            'category': Select(attrs={'class': 'form-control', 'id': 'input-category'}),
            'title': TextInput(attrs={'class': 'form-control', 'id': 'input-title'}),
            'description': Textarea(attrs={'class': 'form-control', 'id': 'input-descritption', 'rows': '3'}),
            'expiry_date': DateInput(attrs={'class': 'form-control', 'id': 'input-expiry_date', 'placeholder': 'jj/mm/aaaa'}),
            'quantity': NumberInput(attrs={'class': 'form-control', 'id': 'input-quantity'}),
            'is_opened': CheckboxInput(attrs={'id': 'input-is_opened' }),
        }

products/views.py
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from products.models import Product, Category
from users.models import User
from products.forms import ProductCreateForm

from django.http import JsonResponse

from django.db.models import Q

from django.contrib.auth.decorators import login_required
#
# class LoginRequiredMixin(object):
#     @classmethod
#     def as_view(cls, **initkwargs):
#         view = super(LoginRequiredMixin, cls).as_view(**initkwargs)
#         return login_required(view)

class ProductListView(ListView):

    def get_queryset(self):
        if "category" in self.request.GET and self.request.GET.get('category').isdigit():
            return self.filter_by_category(self.request.GET.get('category'))
        if "keyword" in self.request.GET:
            return self.filter_by_keyword(self.request.GET.get('keyword'))
        return Product.objects.all()

    def filter_by_keyword(self, keyword):
        category_title_matches = Category.objects.filter(title__icontains=keyword)
        owner_name_matches = User.objects.filter(Q(first_name__icontains=keyword) | Q(last_name__icontains=keyword))
        return Product.objects.filter( Q(title__icontains=keyword) | Q(description__icontains=keyword) | Q(category=category_title_matches) | Q(owner=owner_name_matches) ).distinct().all()

    def filter_by_category(self, category_id):
        category = Category.objects.filter(pk=int(category_id))
        return Product.objects.filter(category=category).all()

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(ProductListView, self).get_context_data(**kwargs)
        # Add in a QuerySet of all the categories
        context['category_list'] = Category.objects.all()
        # Add the create Product form to the QuerySet to be display in a modal
        context['form'] = ProductCreateForm()

        return context

class ProductDetailView(DetailView):

    model = Product

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        # Add in a QuerySet of all the related products
        context['related_product_list'] = Product.objects.filter( Q(category=self.object.category) ).exclude( id=self.object.id )
        return context

class AjaxableResponseMixin(object):
    """
    Mixin to add AJAX support to a form.
    Must be used with an object-based FormView (e.g. CreateView)
    """
    def form_invalid(self, form):
        response = super(AjaxableResponseMixin, self).form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)
        else:
            return response

    def form_valid(self, form):
        # We make sure to call the parent's form_valid() method because
        # it might do some processing (in the case of CreateView, it will
        # call form.save() for example).
        response = super(AjaxableResponseMixin, self).form_valid(form)
        if self.request.is_ajax():
            data = {
                'pk': self.object.pk,
            }
            return JsonResponse(data)
        else:
            return response



class ProductCreateView(AjaxableResponseMixin, CreateView):

    model = Product
    fields = '__all__'

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(ProductCreateView, self).form_valid(form)

products/templates/products/product_detail.html
{% extends "base.html" %}

{% load staticfiles %}

{% block content %}


<!-- main-container start -->
<!-- ================ -->
<section class="main-container">

	<div class="container">
		<div class="row">

			<!-- main start -->
			<!-- ================ -->
			<div class="main col-md-12">

				<!-- page-title start -->
				<!-- ================ -->
				<h1 class="page-title margin-top-clear">{{ product }}</h1>
				<div class="tag">
					<a href="#related-products">{{ product.category }}</a>
				</div>
				<!-- page-title end -->

				<div class="row">
					<hr>
					<hr>
					<div class="blogpost col-md-4">

						<div class="col-sm-8">
							</br></br>
							<label>Date de péremption</label>
						</div>
						<div class="col-sm-4">
							<div class="blogpost-body">
			                    <div class="post-info">
			                      <span class="day">{{ product.expiry_date.day }}</span>
			                      <span class="month">{{ product.expiry_date | date:"M" }} {{ product.expiry_date.year }}</span>
			                    </div>
			                </div>
			            </div>
			            <div class="col-sm-10">
							<label>Quantité</label>
							<p>{{ product.quantity }}</p>
						</div>
						<div class="col-sm-10">
							<label>Déjà ouvert?</label>
							{% if product.is_opened = True %} <p>Oui</p> {% else %} <p>Non</p> {% endif %}
						</div>

					          {% if user.is_authenticated %}
					          <!-- Modal start -->
					          <!-- ============================================================================== -->
					          <!-- Button trigger modal -->
					          <aside class="col-md-1">
					            <button class="btn btn-default pull-right" data-toggle="modal" data-target="#contactUserModal">
					              Contacter {{ product.owner.first_name}}
					            </button>

					            <!-- Modal -->
					            {% include "users/contact_user_form.html" %}

					            <!-- Modal end -->
					          </aside>
					          {% endif %}
					</div>


					<!-- product side start -->
					<aside class="col-md-8">
						<div class="sidebar">
							<div class="side product-item vertical-divider-left">
								<div class="tabs-style-2">
									<!-- Nav tabs -->
									<ul class="nav nav-tabs" role="tablist">
										<li class="active"><a href="#h2tab1" role="tab" data-toggle="tab"><i class="fa fa-file-text-o pr-5"></i>Description</a></li>

										<!-- <li><a href="#h2tab3" role="tab" data-toggle="tab"><i class="fa fa-star pr-5"></i>(3) Reviews</a></li> -->
									</ul>
									<!-- Tab panes -->
									<div class="tab-content padding-top-clear padding-bottom-clear">
										<div class="tab-pane fade in active" id="h2tab1">
											</br>
											<p> {{ product.description }} </p>
										</div>
									</div>
								</div>
							</div>
						</div>
					</aside>
					<!-- product side end -->
				</div>
			</div>

			</div>
			<!-- main end -->


			{% if related_product_list %}
			<!-- section start -->
			<!-- ================ -->
			<div class="section clearfix" id="related-products">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<h2>Dans la catégorie {{ product.category }}</h2>
							<div class="separator-2"></div>
							<div class="col-sm-6 col-md-4 isotope-item web-design">
									<div class="image-box">
										<div class="overlay-container">
											<img src="{% static "categories/images/" %}{{ product.category.get_filename }}" alt="">
											<a href="{% url 'products:index' %}?category={{ category.id }}" class="overlay small">
												<i class="fa fa-link"></i>
												<span>{{ category }}</span>
											</a>
										</div>
									</div>
								</div>
							<div class="row grid-space-20">
								{% for related_product in related_product_list %}
								<div class="col-md-3 col-sm-6">
									<!-- blogpost start -->
									<article class="clearfix blogpost">
										<div class="overlay-container">
											<!-- <img src="images/blog-2.jpg" alt=""> -->
											<div class="overlay">
												<div class="overlay-links">
													<a href="{% url 'products:detail' product.id %}"><i class="fa fa-link"></i></a>
													<a href="" class="popup-img-single" title="image title"><i class="fa fa-search-plus"></i></a>
												</div>
											</div>
										</div>
										<div class="blogpost-body">
											<div class="post-info">
												<span class="day">{{ related_product.expiry_date.day }}</span>
												<span class="month">{{ related_product.expiry_date | date:"M" }} {{ related_product.expiry_date.year }}</span>
											</div>
											<div class="blogpost-content">
												<header>
													<h2 class="title"><a href="{% url 'products:detail' related_product.id %}"> {{ related_product }} </a></h2>
													<div class="submitted"><i class="fa fa-user pr-5"></i> by <a href="#"> {{ related_product.owner }} </a></div>
												</header>
												<!-- <p> {{ product.description }} </p> -->
											</div>
										</div>
									</article>
								</div>
								{% endfor %}
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- section end -->
			{% endif %}

		</div>
	</div>
</section>
<!-- main-container end -->

{% endblock %}

products/templates/products/product_form.html
<div class="modal fade" id="createProductModal" tabindex="-1" role="dialog" aria-labelledby="createProductModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fermer</span></button>
        <h4 class="modal-title" id="createProductModalLabel">Ajouter un produit</h4>
      </div>
      <div class="modal-body">

        <!-- Form start -->
        <form id="create-product-form" class="form-horizontal" role="form" action="{% url 'products:create' %}" method="post">{% csrf_token %}

          {% for field in form %}
          {% if field.errors %}
          <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
            {{ field.errors }}
          </div>
          {% endif %}
          <div class="form-group" id="input-"{{ field.html_name }}>
            <label for="input-"{{ field.html_name }} class="col-sm-2 control-label">{{ field.label }}</label>
            <div class="col-sm-10">
              {{ field }}
            </div>
          </div>
          {% endfor %}

        </form>
        <!-- Form end -->

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-sm btn-dark" data-dismiss="modal">Annuler</button>
        <button id="submit-product-create" type="submit" value="Create" class="btn btn-sm btn-default">Ajouter</button>
      </div>
    </div>
  </div>
</div>

products/templates/products/product_list.html
{% extends "base.html" %}

{% load staticfiles %}

{% block content %}


      <!-- page-intro start-->
      <!-- ================ -->
      <div class="page-intro">
        <div class="section gray-bg text-muted footer-top clearfix">
          <div class="container">
            <div class="row">
              <div class="col-md-12">
                <div class="owl-carousel clients">
                  {% for category in category_list %}
                  {% if not category.title == "Autres" %}
                  <div class="client">
                    <a href="#"><img src="{% static "categories/images/" %}{{ category.get_filename }}" alt=""/></a>
                  </div>
                  {% endif %}
                  {% endfor %}
                </div>
              </div>
              <!-- <div class="col-md-6">
                <blockquote class="inline">
                  <p class="margin-clear">Design is not just what it looks like and feels like. Design is how it works.</p> 
                  <footer><cite title="Source Title">Steve Jobs </cite></footer>
                </blockquote>
              </div>
            </div> -->
          </div>
        </div>

      </div>
      <!-- page-intro end -->

<!-- section start -->
<!-- ================ -->
<!-- main-container start -->
<!-- ================ -->
<section class="main-container">

  <div class="container">
    <div class="row">

      <!-- main start -->
      <!-- ================ -->
      <div class="main col-md-12">

        <!-- page-title start -->
        <!-- ================ -->
        <h1 class="page-title">Produits</h1>
        <div class="separator-2"></div>
        <!-- page-title end -->


        <div class="row">

          <!-- sidebar start -->
          <aside class="col-md-3 col-md-offset-0">
            <div class="sidebar">
              <div class="block clearfix">
                <!-- <h3 class="title">Catégories</h3> -->
                <!-- <div class="separator"></div> -->
                <div class="tags-cloud">
                  <div class="tag">
                    <a href="{% url 'products:index' %}">Tous</a>
                  </div>
                  {% for category in category_list %}
                  <div class="tag">
                    <a href="{% url 'products:index' %}?category={{category.id}}">{{ category.title }}</a>
                  </div>
                  {% endfor %}
                </div>
              </div>
            </div>
            <div class="block clearfix">
              <form role="search" action="{% url 'products:index' %}" method="GET" class="search-box" action="">
                <div class="form-group has-feedback">
                  <input type="text" name="keyword" class="form-control" placeholder="Rechercher">
                  <i class="fa fa-search form-control-feedback"></i>
                </div>
              </form>
            </div>
          </aside>
          <!-- sidebar end -->

          <div class="col-md-6 col-md-offset-1">

            <!-- timeline start -->
            <div class="timeline row">


              {% for product in product_list %}

              <!-- Display month of the expiry date when it changes -->
              {% ifchanged product.expiry_date.month %}
              <div class="timeline-icon hidden-xs"><i class="fa fa-angle-double-up"></i></div>
              <div class="timeline-date-label clearfix"> {{ product.expiry_date | date:"F" }} {{ product.expiry_date.year }}</div>
              {% endifchanged %}

              <!-- timeline item start -->
              {% if forloop.counter|divisibleby:2 %}
              <div class="timeline-item pull-right object-non-visible" data-animation-effect="fadeInUpSmall" data-effect-delay="200">
              {% else %}
              <div class="timeline-item object-non-visible" data-animation-effect="fadeInUpSmall" data-effect-delay="200">
              {% endif %}

                <!-- blogpost start -->
                <article class="clearfix blogpost">
                  <div class="overlay-container">
                    <div class="overlay">
                      <div class="overlay-links">
                        <a href="{% url 'products:detail' product.id %}"><i class="fa fa-link"></i></a>
                      </div>
                    </div>
                  </div>
                  <div class="blogpost-body">
                    <div class="post-info">
                      <span class="day">{{ product.expiry_date.day }}</span>
                      <span class="month">{{ product.expiry_date | date:"M" }} {{ product.expiry_date.year }}</span>
                    </div>
                    <div class="blogpost-content">
                      <header>
                        <h2 class="title"><a href="{% url 'products:detail' product.id %}"> {{ product }} </a></h2>
                      <ul class="center">
                      <!-- <li><i class="fa fa-comment-o pr-5"></i> <a href="#">22 comments</a> |</li>  -->
                      <div class="tag">
                        <h4>
                        <a href="{% url 'products:index' %}?category={{product.category.id}}">{{ product.category }}</a>
                        </h4>
                      </div>
                      </ul>
                        <div class="submitted"><i class="fa fa-user pr-5"></i> by <a href="{% url 'users:detail' product.owner.id %}"> {{ product.owner.first_name }} {{ product.owner.last_name }}</a></div>
                        <!-- <img src="{% static "categories/images/" %}{{ product.category.get_filename }}" alt=""> -->

                      </header>
                      <!-- <p> {{ product.description }} </p> -->
                    </div>
                  </div>
                  <footer class="clearfix">
                    <img src="{% static "categories/images/" %}{{ product.category.get_filename }}" alt="">
                  </footer>
                </article>
                <!-- blogpost end -->

              </div>
              <!-- timeline item end -->

              {% endfor %}


            </div>
            <!-- timeline end -->

          </div>


          {% if user.is_authenticated %}
          <!-- Modal start -->
          <!-- ============================================================================== -->
          <!-- Button trigger modal -->
          <aside class="col-md-1">
            <button id="create-product-button" class="btn btn-default" data-toggle="modal" data-target="#createProductModal">
              Ajouter un produit
            </button>

            <!-- Modal -->
            {% include "products/product_form.html" %}

            <!-- Modal end -->
          </aside>
          {% endif %}



        <!-- pagination start -->
        {% if pages > 1 %}
        <ul class="pagination">
          <li><a href="#">«</a></li>
          {% for }
          <li class="active"><a href="#">{{ pages }} <span class="sr-only">(current)</span></a></li>
          <li><a href="#">2</a></li>
          <li><a href="#">3</a></li>
          <li><a href="#">4</a></li>
          <li><a href="#">5</a></li>
          <li><a href="#">»</a></li>
        </ul>
        {% endif %}
        <!-- pagination end -->

      </div>
      <!-- main end -->

    </div>
  </div>
</section>
<!-- section end -->
<!-- ================ -->
<!-- main-container end -->
<!-- ================ -->


{% endblock %}